<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bt</string>
	</array>
	<key>name</key>
	<string>BType</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#core</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|case|continue|default|do|else|for|if|return|switch|while|export|import|operator)\b</string>
			<key>name</key>
			<string>keyword.control.btype</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(or|and|new|as)\b</string>
			<key>name</key>
			<string>keyword.operator.btype</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|\+|\-|/|\*|%|==|!=|&lt;=|&gt;=|=|&lt;|&gt;|&lt;&lt;|&gt;&gt;|&amp;|\||\^</string>
			<key>name</key>
			<string>keyword.operator.btype</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(func)\b(\w+)(:)(\w+)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.function.btype</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.btype</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definitions.typesep.btype</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.btype</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function.btype</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=:)\w+</string>
					<key>name</key>
					<string>variable.parameter.btype</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+(?=:)</string>
					<key>name</key>
					<string>storage.type.parameter.btype</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_][a-zA-Z0-9_]*)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.btype</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.group.braces.round.function.arguments.btype</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.group.braces.round.function.arguments.btype</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function-call.static.with-args.btype</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=:)[a-zA-Z_][a-zA-Z0-9_]*</string>
					<key>name</key>
					<string>variable.parameter.btype</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_]*(?=:)</string>
					<key>name</key>
					<string>storage.type.parameter.btype</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_][a-zA-Z0-9_]*)\s*(&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.btype</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>braces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brace.round.btype</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brace.round.btype</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.group.braces.round</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brace.square.btype</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brace.square.btype</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.group.braces.square</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brace.curly.btype</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.brace.curly.btype</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.group.braces.curly</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>classes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(object)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.class.btype</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.btype</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.brace.curly.btype</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.class.btype</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.btype</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.type.btype</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.terminator.statement.btype</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(with)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*(;)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(new)\s*(?=\([^())]*\)\s*\{)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.btype</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>meta.function.constructor.btype</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#function-params</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?:[\w\.]+)(:)([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\([^())]*\)\s*\{)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.colon.btype</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.method.btype</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>meta.function.method.btype</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#type</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#function-params</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\([^())]*\)\s*\{)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.method.btype</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>meta.function.method.btype</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#function-params</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.colon.btype</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.btype</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?:[\w&lt;&gt;\.]+)\s*(:)\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*;</string>
							<key>name</key>
							<string>meta.parameter.btype</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#type</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Comments</string>
					<key>match</key>
					<string>#[^\n\r]*</string>
					<key>name</key>
					<string>comment.line.number-sign.btype</string>
				</dict>
			</array>
		</dict>
		<key>core</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#classes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#braces</string>
				</dict>
			</array>
		</dict>
		<key>function-params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.btype</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.btype</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.delimiter.type.colon.btype</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.btype</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?:[\w\.&lt;&gt;]+)(:)([a-zA-Z_][a-zA-Z0-9_]*)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#type</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b&amp;&amp;</string>
					<key>name</key>
					<string>invalid.illegal.binop-and.btype</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|\|</string>
					<key>name</key>
					<string>invalid.illegal.binop-or.btype</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\/\/)</string>
					<key>name</key>
					<string>invalid.illegal.comment.btype</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^	+</string>
					<key>name</key>
					<string>invalid.illegal.tab-indent.btype</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Floats</string>
					<key>match</key>
					<string>\b[1-9][0-9]*\.[0-9]+s?</string>
					<key>name</key>
					<string>constant.numeric.btype</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Floats</string>
					<key>match</key>
					<string>\b0\.[0-9]+s?</string>
					<key>name</key>
					<string>constant.numeric.btype</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Integers</string>
					<key>match</key>
					<string>\b\-?[1-9][0-9]*(?!\.)s?</string>
					<key>name</key>
					<string>constant.numeric.btype</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Integer 0</string>
					<key>match</key>
					<string>\b0(?!\.)</string>
					<key>name</key>
					<string>constant.numeric.btype</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Primitive type literals</string>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.btype</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.btype</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.btype</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.btype</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\.</string>
							<key>name</key>
							<string>constant.character.escape.btype</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.btype</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.btype</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.btype</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\.</string>
							<key>name</key>
							<string>constant.character.escape.btype</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,\s*</string>
					<key>name</key>
					<string>meta.delimiter.object.comma.btype</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>meta.delimiter.object.period.btype</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.statement.btype</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([\w\.]+)(&lt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.btype</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.begin.btype</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.end.btype</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.type.attributed.btype</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>meta.delimiter.parameters.comma.btype</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.btype</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w\.]+)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bool|float|sfloat|uint|func|int|var|str|array)\b</string>
					<key>name</key>
					<string>storage.type.btype</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.btype</string>
	<key>uuid</key>
	<string>c56b4877-01b3-4784-a64e-1ba4f9dd6469</string>
</dict>
</plist>
